package com.example.utils

object LanguageManager {

    fun getString(key: String, isPersian: Boolean): String {
        val faMap = mapOf(
            "app_name" to "پارتینو",
            "subtitle" to "مدیریت هوشمند مطالعه",
            "login" to "ورود",
            "register" to "ثبت‌نام",
            "username" to "نام کاربری",
            "password" to "رمز عبور",
            "name" to "نام و نام خانوادگی",
            "display_name" to "نام نمایشی",
            "username_min_length" to "نام کاربری باید حداقل ۵ کاراکتر باشد",
            "password_min_length" to "رمز عبور باید حداقل ۴ کاراکتر باشد",
            "user_exists" to "این نام کاربری قبلا انتخاب شده است",
            "invalid_credentials" to "نام کاربری یا رمز عبور اشتباه است",
            "have_account_question" to "قبلا حساب داشتین؟",
            "yes" to "بله",
            "no" to "خیر",
            "forgot_password" to "فراموشی رمز عبور؟",
            "support_contact" to "جهت بازیابی رمز عبور یا پشتیبانی با شماره زیر تماس بگیرید:",
            "support_phone" to "09168476659",
            "welcome" to "خوش آمدید",
            "home" to "خانه",
            "groups" to "گروه‌ها",
            "leaders" to "برترین‌ها",
            "settings" to "تنظیمات",
            "total_study" to "مجموع مطالعه",
            "today_study" to "مطالعه امروز",
            "streak" to "پیاپی",
            "days" to "روز",
            "timer" to "تایمر",
            "add_report" to "ثبت گزارش",
            "history" to "تاریخچه",
            "konkur_countdown" to "شمارش معکوس کنکور ۱۴۰۵/۰۴/۱۲",
            "recent_sessions" to "آخرین جلسات مطالعه (۲۴ ساعت اخیر)",
            "announcements" to "اطلاعیه‌ها",
            "stopwatch" to "کرنومتر",
            "countdown" to "شمارش معکوس",
            "start" to "شروع",
            "pause" to "توقف",
            "reset" to "ریست",
            "record_in_report" to "ثبت در گزارش",
            "book_name" to "نام کتاب",
            "topic" to "مبحث",
            "grade" to "پایه تحصیلی",
            "duration_minutes" to "مدت زمان (دقیقه)",
            "test_count" to "تعداد تست",
            "correct_count" to "درست",
            "wrong_count" to "نادرست",
            "notes" to "توضیحات تکمیلی",
            "submit_report" to "ثبت نهایی گزارش",
            "report_saved" to "گزارش با موفقیت ثبت شد",
            "field_required" to "این فیلد اجباری است",
            "invalid_number" to "مقدار عددی نامعتبر است",
            "weekly_chart" to "نمودار مطالعه ۷ روز اخیر",
            "all_reports" to "همه گزارش‌های ثبت شده",
            "daily_summary" to "گزارش کامل روزانه",
            "share" to "اشتراک‌گذاری",
            "save_to_gallery" to "ذخیره عکس گزارش",
            "create_group" to "ایجاد گروه جدید",
            "group_name" to "نام گروه",
            "group_members" to "اعضای گروه",
            "leave_group" to "ترک گروه",
            "add_member" to "افزودن عضو جدید (@)",
            "live_study" to "مطالعه زنده اعضا",
            "top_users" to "۵۰ کاربر برتر ۳ روز اخیر",
            "rank" to "رتبه",
            "dark_mode" to "حالت تاریک (Dark Mode)",
            "language" to "زبان برنامه",
            "allow_group_invites" to "دسترسی عضویت در گروه‌ها",
            "character_name" to "نام شخصیت در گروه‌ها",
            "bio" to "بیوگرافی",
            "save_settings" to "ذخیره تنظیمات",
            "online" to "آنلاین",
            "offline" to "آفلاین",
            "studying" to "در حال مطالعه",
            "delete_confirm" to "آیا از حذف این گزارش مطمئن هستید؟",
            "confirm" to "تأیید",
            "cancel" to "انصراف",
            "hours" to "ساعت",
            "minutes" to "دقیقه"
        )

        val enMap = mapOf(
            "app_name" to "PARTINO",
            "subtitle" to "Smart Study Management",
            "login" to "Login",
            "register" to "Register",
            "username" to "Username",
            "password" to "Password",
            "name" to "Full Name",
            "display_name" to "Display Name",
            "username_min_length" to "Username must be at least 5 characters",
            "password_min_length" to "Password must be at least 4 characters",
            "user_exists" to "This username has already been taken",
            "invalid_credentials" to "Invalid username or password",
            "have_account_question" to "Already have an account?",
            "yes" to "Yes",
            "no" to "No",
            "forgot_password" to "Forgot Password?",
            "support_contact" to "For password recovery or support, please call:",
            "support_phone" to "09168476659",
            "welcome" to "Welcome",
            "home" to "Home",
            "groups" to "Groups",
            "leaders" to "Leaders",
            "settings" to "Settings",
            "total_study" to "Total Study",
            "today_study" to "Today Study",
            "streak" to "Streak",
            "days" to "Days",
            "timer" to "Timer",
            "add_report" to "Add Report",
            "history" to "History",
            "konkur_countdown" to "Konkur 2026 Countdown",
            "recent_sessions" to "Recent Study Sessions (Last 24h)",
            "announcements" to "Announcements",
            "stopwatch" to "Stopwatch",
            "countdown" to "Countdown",
            "start" to "Start",
            "pause" to "Pause",
            "reset" to "Reset",
            "record_in_report" to "Record Report",
            "book_name" to "Book Name",
            "topic" to "Topic",
            "grade" to "Grade/Level",
            "duration_minutes" to "Duration (Minutes)",
            "test_count" to "Total Tests",
            "correct_count" to "Correct",
            "wrong_count" to "Wrong",
            "notes" to "Additional Notes",
            "submit_report" to "Submit Report",
            "report_saved" to "Report saved successfully",
            "field_required" to "This field is required",
            "invalid_number" to "Invalid numeric value",
            "weekly_chart" to "Last 7 Days Study Chart",
            "all_reports" to "All Saved Reports",
            "daily_summary" to "Daily Summary Report",
            "share" to "Share",
            "save_to_gallery" to "Save Report Image",
            "create_group" to "Create New Group",
            "group_name" to "Group Name",
            "group_members" to "Group Members",
            "leave_group" to "Leave Group",
            "add_member" to "Add Member (@)",
            "live_study" to "Members Live Study",
            "top_users" to "Top 50 Users (Last 3 Days)",
            "rank" to "Rank",
            "dark_mode" to "Dark Mode",
            "language" to "Language",
            "allow_group_invites" to "Allow Group Invites",
            "character_name" to "Character Name in Groups",
            "bio" to "Bio",
            "save_settings" to "Save Settings",
            "online" to "Online",
            "offline" to "Offline",
            "studying" to "Studying",
            "delete_confirm" to "Are you sure you want to delete this report?",
            "confirm" to "Confirm",
            "cancel" to "Cancel",
            "hours" to "Hours",
            "minutes" to "Minutes"
        )

        return if (isPersian) {
            faMap[key] ?: key
        } else {
            enMap[key] ?: key
        }
    }
}
